### ISSUE TITLE
请赐教

### ISSUE THREAD

**Issue by FENGYINYUANYOU** [yutingzhao1991/weiqi#2]
请问大神用的什么框架，是用express 吗？

**Comment by yutingzhao1991** [comment]
嗯 对，你可以看看这个项目的依赖。https://github.com/yutingzhao1991/weiqi/blob/master/package.json

依赖只有Lexpress + socket.io

**Comment by FENGYINYUANYOU** [comment]
谢谢你的回复，我是一名大学生，最近在研究围棋算法，希望不吝赐教。

**Comment by FENGYINYUANYOU** [comment]
就围棋在提子的时候，如何高效的提取死子，因为循环遍历的效率太低了，有什么好的方法吗？还有就是评估函数，如何才能更加准确的进行评估？有什么好的算法吗？谢谢前辈

**Comment by yutingzhao1991** [comment]
提取死子好办，每次下子之后最多只要遍历19*19次判断是否还有气即可。你说的效率低可能是在判断是否有气的时候绕了弯路，可以参考我的代码：https://github.com/yutingzhao1991/weiqi/blob/master/public/javascript.js#L16 。每个子有一个life的标记，每次下子的时候遍历一遍下子位置周围相连的区域更新下气的数即可，效率并不低。

至于你说的评估函数我不是很理解，是指AI吗？如果是AI那么围棋的复杂度是很高的，没法像五子棋和象棋那样通过规则或者统计的办法。目前来看就是可以通过alphaGO这样的深度学习的人工智能AI来实现。

**Comment by FENGYINYUANYOU** [comment]
请问前辈，现在写的这个程序支持人机对战吗？

**Comment by yutingzhao1991** [comment]
支持 不过没有可用的ai
